Update resolve_aws_alias values to True/False in README.md
Nike-Inc/gimme-aws-creds pull request #270
Opened 2020-12-17 13:46 UTC by mareimorsy

in the `.okta_aws_login_config` configuration file if you set `resolve_aws_alias = y` it's not going to work properly, you neet to set it as True like that `resolve_aws_alias = True`
## Description

Changed the defalut values from y/n in README.md to True/False
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-02-03 19:10 UTC, bwynsm approved these changes

2021-02-03 19:14 UTC, bwynsm requested changes

2021-02-03 19:14 UTC, bwynsm commented on README.md
> +- resolve_aws_alias - True or False. If yes, gimme-aws-creds will try to resolve AWS account ids with respective alias names (default: n). This option can also be set interactively in the command lin
For this in the action configure, the result in the file will be True or False, but in the action-configure stage, I believe you still have to put "y" or "n" so this change would not be accurate I believe.

2022-10-16 16:37 UTC, epierce commented
Closing since there's been no updates on the changes requested

2022-10-16 16:37 UTC, closed without merging