fix for double challenge factor
Nike-Inc/gimme-aws-creds pull request #385
Opened 2023-02-17 09:04 UTC by kabakakao

These changes had to be made, if you need the stepup-factor. Without these changes the challenge "correctAnswer" isn't shown the second time

## Description
Instead of setting the function `_print_correct_answer` to None this change checks if the answer is the same as in the first attempt. 

## Motivation and Context
In our organization we are using the "correctAnswer" Factor. And the stepup-auth is needed. So the factor came up twice. Without these changes it isn't shown the second time

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-03-23 10:22 UTC, kabakakao commented
@epierce  any chance to get it merged? It is a really annoying issue for us. Please let me know, if I have to change anything.

2023-04-03 17:37 UTC, epierce requested changes

2023-04-27 08:17 UTC, kabakakao commented on gimme_aws_creds/okta.py
> +        self.ui.info("Additional login is needed")
This is just an information, when the stepup_auth is needed.

2023-04-27 16:47 UTC, epierce commented on gimme_aws_creds/okta.py
> +        self.ui.info("Additional login is needed")
Right - but this adds a redundant notification to the user:
```
> gimme-aws-creds
Using password from keyring for eric.pierce@nike.com
Additional login is needed
Multi-factor Authentication required.
```

Also, this change needs to be updated for the current state of the master branch.  The Okta library has been refactored to handle Okta Identity Engine domains.

2023-04-27 17:49 UTC, epierce commented on gimme_aws_creds/okta.py
> +        self.ui.info("Additional login is needed")
Having the 'additional login is needed' notification pop up for everyone doesn't make sense.  If you want that notification when the second MFA challenge happens, you need to build in the logic to show it just in that case. 

Have you looked at the latest version of the project in master?  There have been major changes to the code to handle OIE domains. The functions you've updated have moved to a different file.

2023-04-27 17:59 UTC, kabakakao commented on gimme_aws_creds/okta.py
> +        self.ui.info("Additional login is needed")
Okay. I will take a look at the new master tomorrow. Will you release this new version shortly?

2023-04-27 18:52 UTC, epierce commented on gimme_aws_creds/okta.py
> +        self.ui.info("Additional login is needed")
I'm planning to release v2.6.0 on Monday

2023-07-06 16:49 UTC, kabakakao commented
This is Not needed anymore due to Code changes

2023-07-06 16:49 UTC, closed without merging